-- Insertando algunos registros para que la base de datos no este vacia

INSERT INTO EMPLEADOS (ID,NOMBRE,APELLIDOS,SOCIEDAD) VALUES (1,'Jose Ramon','Porro Nieves',1);
INSERT INTO EMPLEADOS (ID,NOMBRE,APELLIDOS,SOCIEDAD) VALUES (2,'Antonio','Gonzalez Garcia',1);
INSERT INTO EMPLEADOS (ID,NOMBRE,APELLIDOS,SOCIEDAD) VALUES (3,'Jesus','Perea González',1);
INSERT INTO EMPLEADOS (ID,NOMBRE,APELLIDOS,SOCIEDAD) VALUES (4,'Maribel','Vergara',2);

INSERT INTO SOCIEDADES (ID,NOMBRE,CIF) VALUES (1,'INDRA S.A.','A33200203');
INSERT INTO SOCIEDADES (ID,NOMBRE,CIF) VALUES (2,'EL CORTE INGLES S.A.','A33200264');
INSERT INTO SOCIEDADES (ID,NOMBRE,CIF) VALUES (3,'TELEFONICA S.A.','C548584335');
INSERT INTO SOCIEDADES (ID,NOMBRE,CIF) VALUES (4,'VODAFONE TELECOM S.A.','B35938444');