-- Examples

DROP TABLE IF EXISTS EMPLEADOS;
DROP TABLE IF EXISTS SOCIEDADES;


CREATE TABLE EMPLEADOS (
    ID INTEGER IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255) NOT NULL,
    SOCIEDAD INTEGER NOT NULL
);

CREATE TABLE SOCIEDADES (
    ID INTEGER IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    CIF VARCHAR(255) NOT NULL
);

CREATE TABLE COURSCUST(
    CUSTOMER_ID INTEGER,
    COURSE_ID INTEGER,
    PRIMARY KEY (CUSTOMER_ID,COURSE_ID)
);